/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author WS
 */
public class Mainframe extends javax.swing.JFrame {
    
    double firstnum;
    double secondnum;
    double result;
    String operations;
    
    public Mainframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbloutput = new javax.swing.JLabel();
        btlmodulo = new javax.swing.JButton();
        btnce = new javax.swing.JButton();
        btndivide = new javax.swing.JButton();
        btncl = new javax.swing.JButton();
        btnseven = new javax.swing.JButton();
        btnnine = new javax.swing.JButton();
        btnmultiply = new javax.swing.JButton();
        btnfour = new javax.swing.JButton();
        btneigth = new javax.swing.JButton();
        btnfive = new javax.swing.JButton();
        btnsix = new javax.swing.JButton();
        btnsubtraction = new javax.swing.JButton();
        btnone = new javax.swing.JButton();
        btntwo = new javax.swing.JButton();
        btnthree = new javax.swing.JButton();
        btnaddition = new javax.swing.JButton();
        btnnegativepositive = new javax.swing.JButton();
        btnzero = new javax.swing.JButton();
        btndecimalpoint = new javax.swing.JButton();
        btnequals = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        lbloutput.setBackground(new java.awt.Color(153, 153, 255));
        lbloutput.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        lbloutput.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbloutput.setOpaque(true);

        btlmodulo.setBackground(new java.awt.Color(204, 204, 204));
        btlmodulo.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        btlmodulo.setText("%");
        btlmodulo.setOpaque(true);
        btlmodulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlmoduloActionPerformed(evt);
            }
        });

        btnce.setBackground(new java.awt.Color(204, 204, 204));
        btnce.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        btnce.setText("CE");
        btnce.setOpaque(true);
        btnce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnceActionPerformed(evt);
            }
        });

        btndivide.setBackground(new java.awt.Color(204, 204, 204));
        btndivide.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        btndivide.setText("/");
        btndivide.setOpaque(true);
        btndivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndivideActionPerformed(evt);
            }
        });

        btncl.setBackground(new java.awt.Color(204, 204, 204));
        btncl.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        btncl.setText("C");
        btncl.setOpaque(true);
        btncl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclActionPerformed(evt);
            }
        });

        btnseven.setBackground(new java.awt.Color(204, 204, 204));
        btnseven.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        btnseven.setText("7");
        btnseven.setOpaque(true);
        btnseven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsevenActionPerformed(evt);
            }
        });

        btnnine.setBackground(new java.awt.Color(204, 204, 204));
        btnnine.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        btnnine.setText("9");
        btnnine.setOpaque(true);
        btnnine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnineActionPerformed(evt);
            }
        });

        btnmultiply.setBackground(new java.awt.Color(204, 204, 204));
        btnmultiply.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        btnmultiply.setText("x");
        btnmultiply.setOpaque(true);
        btnmultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmultiplyActionPerformed(evt);
            }
        });

        btnfour.setBackground(new java.awt.Color(204, 204, 204));
        btnfour.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        btnfour.setText("4");
        btnfour.setOpaque(true);
        btnfour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfourActionPerformed(evt);
            }
        });

        btneigth.setBackground(new java.awt.Color(204, 204, 204));
        btneigth.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        btneigth.setText("8");
        btneigth.setOpaque(true);
        btneigth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneigthActionPerformed(evt);
            }
        });

        btnfive.setBackground(new java.awt.Color(204, 204, 204));
        btnfive.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        btnfive.setText("5");
        btnfive.setOpaque(true);
        btnfive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfiveActionPerformed(evt);
            }
        });

        btnsix.setBackground(new java.awt.Color(204, 204, 204));
        btnsix.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        btnsix.setText("6");
        btnsix.setOpaque(true);
        btnsix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsixActionPerformed(evt);
            }
        });

        btnsubtraction.setBackground(new java.awt.Color(204, 204, 204));
        btnsubtraction.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        btnsubtraction.setText("-");
        btnsubtraction.setOpaque(true);
        btnsubtraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubtractionActionPerformed(evt);
            }
        });

        btnone.setBackground(new java.awt.Color(204, 204, 204));
        btnone.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        btnone.setText("1");
        btnone.setOpaque(true);
        btnone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoneActionPerformed(evt);
            }
        });

        btntwo.setBackground(new java.awt.Color(204, 204, 204));
        btntwo.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        btntwo.setText("2");
        btntwo.setOpaque(true);
        btntwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntwoActionPerformed(evt);
            }
        });

        btnthree.setBackground(new java.awt.Color(204, 204, 204));
        btnthree.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        btnthree.setText("3");
        btnthree.setOpaque(true);
        btnthree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthreeActionPerformed(evt);
            }
        });

        btnaddition.setBackground(new java.awt.Color(204, 204, 204));
        btnaddition.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        btnaddition.setText("+");
        btnaddition.setOpaque(true);
        btnaddition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadditionActionPerformed(evt);
            }
        });

        btnnegativepositive.setBackground(new java.awt.Color(204, 204, 204));
        btnnegativepositive.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        btnnegativepositive.setText("+/-");
        btnnegativepositive.setOpaque(true);
        btnnegativepositive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnegativepositiveActionPerformed(evt);
            }
        });

        btnzero.setBackground(new java.awt.Color(204, 204, 204));
        btnzero.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        btnzero.setText("0");
        btnzero.setOpaque(true);
        btnzero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnzeroActionPerformed(evt);
            }
        });

        btndecimalpoint.setBackground(new java.awt.Color(204, 204, 204));
        btndecimalpoint.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        btndecimalpoint.setText(".");
        btndecimalpoint.setOpaque(true);
        btndecimalpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndecimalpointActionPerformed(evt);
            }
        });

        btnequals.setBackground(new java.awt.Color(204, 204, 204));
        btnequals.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        btnequals.setText("=");
        btnequals.setOpaque(true);
        btnequals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnequalsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btncl, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btlmodulo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btndivide, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnfour, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnfive, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnsix, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnsubtraction, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnseven, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btneigth, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnnine, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnmultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnone, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btntwo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnthree, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnaddition, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnnegativepositive, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnzero, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btndecimalpoint, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnequals, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lbloutput, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(btnce, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(295, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lbloutput, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btlmodulo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btndivide, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btncl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnseven, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnnine, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnmultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btneigth, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnfour, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfive, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsix, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsubtraction, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnone, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntwo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnthree, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaddition, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnequals, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndecimalpoint, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnzero, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnegativepositive, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(127, 127, 127)
                    .addComponent(btnce, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(337, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoneActionPerformed
        String Enternumber = lbloutput.getText()+ btnone.getText();
        lbloutput.setText(Enternumber);
    }//GEN-LAST:event_btnoneActionPerformed

    private void btntwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntwoActionPerformed
        String Enternumber = lbloutput.getText()+ btntwo.getText();
        lbloutput.setText(Enternumber);// TODO add your handling code here:
    }//GEN-LAST:event_btntwoActionPerformed

    private void btnthreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthreeActionPerformed
        String Enternumber = lbloutput.getText()+ btnthree.getText();
        lbloutput.setText(Enternumber);// TODO add your handling code here:
    }//GEN-LAST:event_btnthreeActionPerformed

    private void btnfourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfourActionPerformed
        String Enternumber = lbloutput.getText()+ btnfour.getText();
        lbloutput.setText(Enternumber);// TODO add your handling code here:
    }//GEN-LAST:event_btnfourActionPerformed

    private void btnfiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfiveActionPerformed
        String Enternumber = lbloutput.getText()+ btnfive.getText();
        lbloutput.setText(Enternumber);// TODO add your handling code here:
    }//GEN-LAST:event_btnfiveActionPerformed

    private void btnsixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsixActionPerformed
        String Enternumber = lbloutput.getText()+ btnsix.getText();
        lbloutput.setText(Enternumber);// TODO add your handling code here:
    }//GEN-LAST:event_btnsixActionPerformed

    private void btnsevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsevenActionPerformed
        String Enternumber = lbloutput.getText()+ btnseven.getText();
        lbloutput.setText(Enternumber);// TODO add your handling code here:
    }//GEN-LAST:event_btnsevenActionPerformed

    private void btneigthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneigthActionPerformed
        String Enternumber = lbloutput.getText()+ btneigth.getText();
        lbloutput.setText(Enternumber);// TODO add your handling code here:
    }//GEN-LAST:event_btneigthActionPerformed

    private void btnnineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnineActionPerformed
        String Enternumber = lbloutput.getText()+ btnnine.getText();
        lbloutput.setText(Enternumber);// TODO add your handling code here:
    }//GEN-LAST:event_btnnineActionPerformed

    private void btnzeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnzeroActionPerformed
        String Enternumber = lbloutput.getText()+ btnzero.getText();
        lbloutput.setText(Enternumber);// TODO add your handling code here:
    }//GEN-LAST:event_btnzeroActionPerformed

    private void btnadditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadditionActionPerformed
        firstnum = Double.parseDouble(lbloutput.getText());
        lbloutput.setText("");
        operations = "+" ;// TODO add your handling code here:
    }//GEN-LAST:event_btnadditionActionPerformed

    private void btnsubtractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubtractionActionPerformed
         firstnum = Double.parseDouble(lbloutput.getText());
        lbloutput.setText("");
        operations = "-" ;// TODO add your handling code here:
    }//GEN-LAST:event_btnsubtractionActionPerformed

    private void btnmultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmultiplyActionPerformed
         firstnum = Double.parseDouble(lbloutput.getText());
        lbloutput.setText("");
        operations = "*" ;// TODO add your handling code here:
    }//GEN-LAST:event_btnmultiplyActionPerformed

    private void btndivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndivideActionPerformed
        firstnum = Double.parseDouble(lbloutput.getText());
        lbloutput.setText("");
        operations = "/" ;
    }//GEN-LAST:event_btndivideActionPerformed

    private void btnnegativepositiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnegativepositiveActionPerformed
        double ops = Double.parseDouble(String.valueOf(lbloutput.getText()));
        ops = ops * (-1);
        lbloutput.setText(String.valueOf(ops));// TODO add your handling code here:
    }//GEN-LAST:event_btnnegativepositiveActionPerformed

    private void btnequalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnequalsActionPerformed
        String answer;
        secondnum = Double.parseDouble(lbloutput.getText());
        if (operations == "+"){
            result = firstnum + secondnum;
            answer = String.format("%.0f",result);
            lbloutput.setText(answer);
        }else if (operations == "-"){
            result = firstnum - secondnum;
            answer = String.format("%.0f",result);
            lbloutput.setText(answer);  
        }else if (operations == "*"){
            result = firstnum * secondnum;
            answer = String.format("%.0f",result);
            lbloutput.setText(answer);
        }else if (operations == "/"){
            result = firstnum / secondnum;
            answer = String.format("%.0f",result);
            lbloutput.setText(answer);
        }else if (operations == "%"){
            result = firstnum % secondnum;
            answer = String.format("%.0f",result);
            lbloutput.setText(answer);
        }
    }//GEN-LAST:event_btnequalsActionPerformed

    private void btnclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclActionPerformed
        lbloutput.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_btnclActionPerformed

    private void btnceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnceActionPerformed
        String backspace = null;
        
        if(lbloutput.getText().length() >0){
            StringBuilder strB = new StringBuilder(lbloutput.getText());
            strB.deleteCharAt(lbloutput.getText().length()- 1);
            backspace = strB.toString();
            lbloutput.setText(backspace);
        }
    }//GEN-LAST:event_btnceActionPerformed

    private void btlmoduloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlmoduloActionPerformed
        firstnum = Double.parseDouble(lbloutput.getText());
        lbloutput.setText("");
        operations = "%";// TODO add your handling code here:
    }//GEN-LAST:event_btlmoduloActionPerformed

    private void btndecimalpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndecimalpointActionPerformed
        String EnterNumber = lbloutput.getText() + btndecimalpoint.getText();
        lbloutput.setText(EnterNumber);
    }//GEN-LAST:event_btndecimalpointActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btlmodulo;
    private javax.swing.JButton btlmodulo1;
    private javax.swing.JButton btnaddition;
    private javax.swing.JButton btnce;
    private javax.swing.JButton btnce1;
    private javax.swing.JButton btncl;
    private javax.swing.JButton btncl3;
    private javax.swing.JButton btncl4;
    private javax.swing.JButton btncl5;
    private javax.swing.JButton btndecimalpoint;
    private javax.swing.JButton btndivide;
    private javax.swing.JButton btndivide1;
    private javax.swing.JButton btneigth;
    private javax.swing.JButton btnequals;
    private javax.swing.JButton btnfive;
    private javax.swing.JButton btnfour;
    private javax.swing.JButton btnmultiply;
    private javax.swing.JButton btnnegativepositive;
    private javax.swing.JButton btnnine;
    private javax.swing.JButton btnone;
    private javax.swing.JButton btnseven;
    private javax.swing.JButton btnsix;
    private javax.swing.JButton btnsubtraction;
    private javax.swing.JButton btnthree;
    private javax.swing.JButton btntwo;
    private javax.swing.JButton btnzero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbloutput;
    private javax.swing.JLabel lbloutput1;
    // End of variables declaration//GEN-END:variables
}
